### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by Suntrie** [vldF/UnsignedBigInteger#1]
1. В toString, вроде бы, можно обойтись  только String.format;
2. Не вполне очевидно, зачем Вам в subtract нужен floor/ modFloor - почему нельзя обойтись обычным целочисленным делением?
3. Если говорить про copy - то он у Вас сейчас, по сути, реализует [конструктор копирования (или clone)](https://dzone.com/articles/java-cloning-copy-constructor-vs-cloning) -> лучше вынести его в соответствующий метод;
4. Если говорить про DivModResult - то тут что-то пошло не так с областями видимости (класс публичный, но мы ни создать объекты снаружи не можем, ни получить доступ к полям). По впечатлению, он должен скорее относиться к деталям реализации и впринципе не торчать наружу. Также с точки зрения организации кода здесь имеет смысл посмотреть в сторону различных видов [вложенных классов](http://tutorials.jenkov.com/java/nested-classes.html);
5. Поправьте меня, но в times, который принимает long, может быть переполнением (при подаче Long.MAX_VALUE, например);
6. Алгоритм, реализованный в divMod требует либо тщательного пояснения  в комментариях, либо (лучше) - введения значащих имён переменных и вспомогательных методов с "говорящими" названиями. Пока анализу поддаётся с трудом.

**Comment by vldF** [comment]
2. Я использую тут этот метод, так как тут нужно немного иначе получать остаток (не как в случае с обычным, правильным остатком от деления, %). Подробнее можно почитать [тут](https://stackoverflow.com/questions/14769943/java-is-there-a-method-for-euclidean-or-floored-modulo). Да, можно использовать и обычное деление, но такой подход мне нравится больше

Насчёт всего остального - согласен, исправлю (прокомментирую) в выходные

**Comment by vldF** [comment]
1. А как можно использовать String.format? Я сейчас переписал на стримы, стало лучше

**Comment by vldF** [comment]
5. Да, действительно, в некоторых ситуациях может быть переполнение. Поставил ограничение на other в виде Integer.MAX_VALUE

**Comment by vldF** [comment]
> 1. В toString, вроде бы, можно обойтись  только String.format;
> 2. Не вполне очевидно, зачем Вам в subtract нужен floor/ modFloor - почему нельзя обойтись обычным целочисленным делением?
> 3. Если говорить про copy - то он у Вас сейчас, по сути, реализует [конструктор копирования (или clone)](https://dzone.com/articles/java-cloning-copy-constructor-vs-cloning) -> лучше вынести его в соответствующий метод;
> 4. Если говорить про DivModResult - то тут что-то пошло не так с областями видимости (класс публичный, но мы ни создать объекты снаружи не можем, ни получить доступ к полям). По впечатлению, он должен скорее относиться к деталям реализации и впринципе не торчать наружу. Также с точки зрения организации кода здесь имеет смысл посмотреть в сторону различных видов [вложенных классов](http://tutorials.jenkov.com/java/nested-classes.html);
> 5. Поправьте меня, но в times, который принимает long, может быть переполнением (при подаче Long.MAX_VALUE, например);
> 6. Алгоритм, реализованный в divMod требует либо тщательного пояснения  в комментариях, либо (лучше) - введения значащих имён переменных и вспомогательных методов с "говорящими" названиями. Пока анализу поддаётся с трудом.

Всё, я внёс правки

**Comment by Suntrie** [comment]
1. Здесь Вы правы. И стало заметно лучше как минимум, потому, что исчезла операция вставки в начало строки;

2. Поняла, спасибо (jfyi, некритично, но по возможности лучше настраивать импорты так, чтобы не приходилось писать имя класса);

3. По впечатлению, с clone Вы пока разобрались не до конца (во всяком случае, логика его работы будет отличаться относительно первоначальной реализации метода copy - обращаю Ваше внимание, что для полей ссылочных типов по умолчанию осуществляется shallow копирование);

4. По текущей реализации DivModResult согласна, хотя с точки зрения стиля лучше бы дописать equals/hashCode/toString и для вложенного класса тоже - он все еще моделирует данные, а не чисто служебный;

5. Ок;

6. Спасибо, поняла. Так же, как Вы избавились от [вставки в начало списка в п.1](https://habr.com/ru/post/128269/), от нее лучше бы избавиться и здесь (неэффективно). Кроме этого - переборные методы = ресурсоемко (даже если это бисекция). Здесь вроде можно проще?

**Comment by Suntrie** [comment]
Откройте, пожалуйста, обратно issue - запутаемся.

**Comment by vldF** [comment]
fixed

**Comment by vldF** [comment]
6. Тут происходит не полный перебор, а подбор цифр. Насколько я знаю, деление столбиком иначе организовать нельзя. Перебором в данном случае происходит деление большого числа на большое (а ответ получается в виде цифры, инта). Скорее всего, есть и более оптимальные методы решения, не привязанные к делению в столбик, но они достаточно сложны для реализации
