### ISSUE TITLE
.gitgnore

### ISSUE THREAD

**Issue by Suntrie** [vldF/UnsignedBigInteger#2]
Что-то лишнее попало в зону отслеживания СКВ. Стоит посмотреть в сторону git -rm + конфигурации .gitgnore (UIDesigner расшаривать точно нет смысла - как правило, СКВ нужна для обмена версиями кода между коллегами, а это Ваши кастомные настройки отображения, инспекции, по всей видимости, тоже, и т. д.).

**Comment by vldF** [comment]
Похоже, что исправил

**Comment by Suntrie** [comment]
Реализуйте, пожалуйста, проект с использованием либо Maven, либо Gradle: Идея дает для них оболочку, но сами по себе они не зависят от используемого инструмента разработки. Материалы по howto посылала старосте. Что нужно в СКВ, а без чего можно обойтись в подобных случаях - можно посмотреть в файле "Вопросы и ответы". inspectionProfiles вроде не нужны ни в одной из версий развития событий, например. Зависимости от Котлиновских библиотек в проекте на Java тоже настораживают)

**Comment by Suntrie** [comment]
Пожалуйста, переоткройте issues и не закрывайте их самостоятельно в дальнейшем, а то мы с Вами рискуем запутаться в процессе работы.

**Comment by vldF** [comment]
fixed
